#!/usr/bin/env python

"""Pentagonal numbers are generated by the formula, Pn=n(3n - 1)/2. The
first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference is pentagonal and D = |Pk - Pj| is minimised; what is the value
of D?
"""

import itertools

class Pentagonals:
    def __init__(self, limit):
        self.pentagonals = {}
        self.pentagonal_set = set([])
        for i in range(1, limit):
            pentagonal = i * (3*i-1) / 2
            self.pentagonals[i] = pentagonal
            self.pentagonal_set.add(pentagonal)

    def nth(self, n):
        return self.pentagonals[n]

    def has(self, number):
        return number in self.pentagonal_set


if __name__ == "__main__":
    limit = 10000
    pentagonals = Pentagonals(limit)
    matches = []
    for pair in itertools.combinations(range(1, limit), 2):
        p1 = pentagonals.nth(pair[0])
        p2 = pentagonals.nth(pair[1])
        if pentagonals.has(p1 + p2) and pentagonals.has(p2 - p1):
            print p2 - p1
            break
