#!/usr/bin/env python

"""Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def triangle(n):
    return n*(n+1)/2

def pentagonal(n):
    return n*(3*n-1)/2


def hexagonal(n):
    return n*(2*n-1)


if __name__ == "__main__":
    triangles = set([])
    pentagonals = set([])
    hexagonals = set([])
    for i in xrange(2, 60000):
        triangles.add(triangle(i))
        pentagonals.add(pentagonal(i))
        hexagonals.add(hexagonal(i))
        
    a = triangles.intersection(pentagonals)
    b = triangles.intersection(hexagonals)
    print max(a.intersection(b))
