"""Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def sum_even_fibs(max_val):
    x = 1
    y = 2
    sum = 0
    while y <= max_val:
        if y % 2 == 0: sum += y
        tmp = y
        y = x+y
        x = tmp

    return sum
        



if __name__ == "__main__":
    print sum_even_fibs(4000000)

